CREATE TABLE IF NOT EXISTS `exercicio16` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `criterion_name` VARCHAR(100) NOT NULL,
  `score` DECIMAL(3,1) NOT NULL,
  `classification` VARCHAR(20) NOT NULL,
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;